ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE REGIONAL_MOCK.BKCLI (
    CLI      VARCHAR2(50 CHAR)  PRIMARY KEY,
    NID      VARCHAR2(50 CHAR),
    NOMREST  VARCHAR2(200 CHAR)
);

CREATE TABLE REGIONAL_MOCK.BKCOM (
    AGE  VARCHAR2(20 CHAR) NOT NULL,
    NCP  VARCHAR2(30 CHAR) NOT NULL,
    CLC  VARCHAR2(10 CHAR) NOT NULL,
    CLI  VARCHAR2(50 CHAR) NOT NULL,
    DEV  VARCHAR2(10 CHAR) NOT NULL,
    IFE  CHAR(1 CHAR)      NOT NULL,
    CFE  CHAR(1 CHAR)      NOT NULL,
    CONSTRAINT PK_BKCOM PRIMARY KEY (AGE, NCP, CLC),
    CONSTRAINT FK_BKCOM_BKCLI FOREIGN KEY (CLI) REFERENCES REGIONAL_MOCK.BKCLI(CLI)
);

CREATE TABLE REGIONAL_MOCK.BKTELCLI (
    CLI  VARCHAR2(50 CHAR) NOT NULL,
    NUM  VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT FK_BKTELCLI_BKCLI FOREIGN KEY (CLI) REFERENCES REGIONAL_MOCK.BKCLI(CLI)
);

CREATE TABLE REGIONAL_MOCK.BKEMACLI (
    CLI    VARCHAR2(50 CHAR)  NOT NULL,
    EMAIL  VARCHAR2(254 CHAR) NOT NULL,
    CONSTRAINT FK_BKEMACLI_BKCLI FOREIGN KEY (CLI) REFERENCES REGIONAL_MOCK.BKCLI(CLI)
);

INSERT INTO REGIONAL_MOCK.BKCLI (CLI, NID, NOMREST)
VALUES ('CUS-001', 'NIU-001', 'Jane Doe');

INSERT INTO REGIONAL_MOCK.BKCOM (AGE, NCP, CLC, CLI, DEV, IFE, CFE)
VALUES ('001', '123456', '7', 'CUS-001', '001', 'N', 'N');

INSERT INTO REGIONAL_MOCK.BKTELCLI (CLI, NUM)
VALUES ('CUS-001', '+237600000000');

INSERT INTO REGIONAL_MOCK.BKEMACLI (CLI, EMAIL)
VALUES ('CUS-001', 'jane@example.com');

INSERT INTO REGIONAL_MOCK.BKCLI (CLI, NID, NOMREST)
VALUES ('CUS-INACTIVE', 'NIU-INACTIVE', 'Inactive Customer');

INSERT INTO REGIONAL_MOCK.BKCOM (AGE, NCP, CLC, CLI, DEV, IFE, CFE)
VALUES ('001', '999999', '1', 'CUS-INACTIVE', '001', 'Y', 'Y');

COMMIT;
